import { defaultEditorLocalization, EditorLocalization } from '../localization';

// Croatian localization
const localization: EditorLocalization = {
	...defaultEditorLocalization,
	help: 'Pomoć',
	helpHidden: 'Pomoć skrivena',
	next: 'Dalje',
	previous: 'Natrag',
	close: 'Zatvori',
	helpScreenNavigationHelp: 'Klikni na kontrolu za više informacija.',
	helpControlsAccessibilityLabel: 'Kontrole: Aktiviraj kontrolu za prikaz pomoći.',
	pen: 'Olovka',
	eraser: 'Gumica',
	select: 'Odabir',
	handTool: 'Pomicanje',
	zoom: 'Zumiranje',
	image: 'Slika',
	reformatSelection: 'Oblikuj odabir',
	inputAltText: 'Alt-tekst',
	decreaseImageSize: 'Smanji veličinu',
	resetImage: 'Resetiraj',
	chooseFile: 'Odaberi datoteku',
	dragAndDropHereOrBrowse: 'Povuci i ispusti ovdje\nili\n{{pretraži}}',
	submit: 'Pošalji',
	addAll: 'Dodaj sve',
	cancel: 'Odustani',
	resetView: 'Resetiraj prikaz',
	thicknessLabel: 'Debljina',
	colorLabel: 'Boja',
	textSize: 'Veličina',
	resizeImageToSelection: 'Prilagodi veličinu slike odabiru',
	deleteSelection: 'Izbriši odabir',
	duplicateSelection: 'Dupliciraj odabir',
	exit: 'Zatvori',
	save: 'Spremi',
	undo: 'Poništi',
	redo: 'Ponovi',
	fullStrokeEraser: 'Gumica punog poteza',
	selectPenType: 'Vrsta olovke',
	selectShape: 'Oblik',
	pickColorFromScreen: 'Odaberi boju s ekrana',
	clickToPickColorAnnouncement: 'Klikni na ekran za biranje boje',
	colorSelectionCanceledAnnouncement: 'Odabir boje je otkazan',
	selectionTool__lassoSelect: 'Prostoručni odabir',
	selectionTool__lassoSelect__help:
		'Kad je uključeno, povlačenjem se stvara prostoručni (laso) odabir.',
	selectionToolKeyboardShortcuts:
		'Alat za odabir: koristi tipke sa strelicama za pomicanje odabranih stavki, mala/velika slova „i“ i „o“ za mijenjanje veličine.',
	documentProperties: 'Stranica',
	backgroundColor: 'Boja pozadine',
	imageWidthOption: 'Širina',
	imageHeightOption: 'Visina',
	useGridOption: 'Rešetka',
	enableAutoresizeOption: 'Automatska prilagodba veličine',
	toggleOverflow: 'Više',
	about: 'Informacije',
	inputStabilization: 'Stabilizacija',
	strokeAutocorrect: 'Automatsko ispravljanje',
	pressureSensitivity: 'Pritisak',
	touchPanning: 'Pomicanje dodirom',
	roundedTipPen: 'Okrugli vrh',
	roundedTipPen2: 'Polilinija',
	flatTipPen: 'Ravni vrh',
	arrowPen: 'Strelica',
	linePen: 'Linija',
	outlinedRectanglePen: 'Pravokutnik s konturom',
	filledRectanglePen: 'Ispunjeni pravokutnik',
	outlinedCirclePen: 'Kružnica s konturom',
	lockRotation: 'Zaključaj okretanje',
	paste: 'Zalijepi',
	errorImageHasZeroSize: 'Greška: slika nema veličinu',
	describeTheImage: 'Opis slike',
	fileInput__loading: 'Učitavanje …',
	fileInput__andNMoreFiles: (n) => `(… još ${n})`,
	penDropdown__baseHelpText: 'Ovaj alat crta oblike ili prostoručno crtane linije.',
	penDropdown__colorHelpText: 'Mijenja boju olovke',
	penDropdown__thicknessHelpText: 'Mijenja debljinu poteza crtan olovkom.',
	penDropdown__penTypeHelpText:
		'Mijenja stil olovke.\n\nMože se odabrati stil „olovka” ili „oblik”. „Olovka” služi za prostoručno crtanje. „Oblik” služi za crtanje oblika.',
	penDropdown__autocorrectHelpText:
		'Pretvara približne prostoručne linije i pravokutnike u pravilne oblike.\n\nOlovka se mora držati mirno na kraju poteza kako bi se pokrenulo ispravljanje.',
	penDropdown__stabilizationHelpText:
		'Crta glađe poteze.\n\nTakođer dodaje kratko kašnjenje između miša/digitalne olovke i poteza.',
	penDropdown__pressureSensitivityHelpText:
		'Mijenja debljinu poteza ovisno o jačini pritiska pri korištenju kompatibilnog uređaja poput digitalne olovke.',
	handDropdown__baseHelpText: 'Ovaj alat služi za pomicanje, okretanje i zumiranje uređivača.',
	handDropdown__zoomInHelpText: 'Povećava prikaz.',
	handDropdown__zoomOutHelpText: 'Smanjuje prikaz.',
	handDropdown__resetViewHelpText: 'Vraća razinu zumiranja na 100 % i resetira pomak.',
	handDropdown__zoomDisplayHelpText:
		'Prikazuje trenutačnu razinu zumiranja. 100 % prikazuje sliku u stvarnoj veličini.',
	handDropdown__touchPanningHelpText:
		'Kada je uključeno, geste na dodirnom ekranu pomiču sliku umjesto odabira ili crtanja.',
	handDropdown__lockRotationHelpText:
		'Kada je uključeno, sprečava okretanja ekrana gestama dodira.',
	eraserDropdown__baseHelpText: 'Ovaj alat uklanja poteze, slike i tekst ispod kursora.',
	eraserDropdown__thicknessHelpText: 'Mijenja veličinu gumice.',
	eraserDropdown__fullStrokeEraserHelpText:
		'U modusu punog poteza brišu se cijeli oblici.\n\nKada je modus isključen, oblici se mogu djelomično brisati.',
	selectionDropdown__baseHelpText: 'Bira sadržaj i mijenja odabir',
	selectionDropdown__resizeToHelpText:
		'Obrezuje crtež na veličinu trenutačnog odabira.\n\nAko je automatska prilagodba veličine uključena, isključit će se.',
	selectionDropdown__deleteHelpText: 'Briše odabrane stavke.',
	selectionDropdown__duplicateHelpText: 'Stvara kopiju odabranih stavki.',
	selectionDropdown__changeColorHelpText: 'Mijenja boju odabranih stavki.',
	pageDropdown__baseHelpText: 'Upravlja bojom pozadine, mustrom i veličinom platna.',
	pageDropdown__backgroundColorHelpText: 'Mijenja boju pozadine platna.',
	pageDropdown__gridCheckboxHelpText: 'Uključuje/isključuje mustru rešetke pozadine.',
	pageDropdown__autoresizeCheckboxHelpText:
		'Kada je uključeno, stranica se širi kako bi prilagodila crtežu.\n\nKada je isključeno, stranica je vidljiva i njezina se veličina može ručno postaviti.',
	pageDropdown__aboutButtonHelpText:
		'Prikazuje verziju, informacije o otklanjanju grešaka i ostale podatke.',
	colorPickerPipetteHelpText: 'Bira boju s ekrana.',
	colorPickerToggleHelpText: 'Otvara/zatvara birač boja.',
	closeSidebar: (toolName) => `Zatvori bočnu traku za ${toolName}`,
	dropdownShown: (toolName) => `Izbornik za ${toolName} prikazan`,
	dropdownHidden: (toolName) => `Izbornik za ${toolName} skriven`,
	zoomLevel: (zoomPercent) => `Zumiranje ${zoomPercent} %`,
	colorChangedAnnouncement: (color) => `Boja je promijenjena u ${color}`,
	imageSize: (size, units) => `Veličina slike ${size} ${units}`,
	imageLoadError: (message) => `Greška pri učitavanju slike ${message}`,
	penTool: (penId) => `Olovka ${penId}`,
	selectionTool: 'Odabir',
	selectAllTool: 'Prečac za „Odaberi sve”',
	eraserTool: 'Gumica',
	touchPanTool: 'Micanje dodirom',
	twoFingerPanZoomTool: 'Micanje i zumiranje',
	undoRedoTool: 'Poništi/Ponovi',
	rightClickDragPanTool: 'Povlačenje desnim klikom',
	pipetteTool: 'Odaberi boju s ekrana',
	keyboardPanZoom: 'Tipkovni prečaci za pomicanje/zumiranje',
	selectionMenu__show: 'Prikaži izbornik za odabir',
	selectionMenu__copyToClipboard: 'Kopiraj u međuspremnik',
	selectionMenu__duplicate: 'Dupliciraj',
	selectionMenu__delete: 'Izbriši',
	selectionMenu__paste: 'Zalijepi',
	copyPasteError__heading: 'Kopiraj/Zalijepi',
	copyPasteError__description: 'Dogodila se greška – ovaj alat možda nema pristup međuspremniku.',
	copyPasteError__errorDetails: 'Prikaži grešku',
	copyPasteError__pasteRetry: 'Za ponovni pokušaj, zalijepi u donje polje za unos:',
	copyPasteError__copyRetry: 'Za ponovni pokušaj, kopiraj tekst u donjem polju za unos:',
	copyPasteError__copyMe: 'Kopiraj me!',
	autocorrectedTo: (strokeDescription) => `Automatski ispravljeno u ${strokeDescription}`,
	autocorrectionCanceled: 'Automatsko ispravljanje otkazano',
	textTool: 'Tekst',
	enterTextToInsert: 'Tekst za umetanje',
	changeTool: 'Promijeni alat',
	pasteHandler: 'Upravljač kopiranja i lijepljenja',
	soundExplorer: 'Zvučno istraživanje slike',
	disableAccessibilityExploreTool: 'Isključi zvučno istraživanje',
	enableAccessibilityExploreTool: 'Uključi zvučno istraživanje',
	soundExplorerUsageAnnouncement:
		'Zvučno istraživanje slike uključeno: klikni/povuci ekran za reprodukciju zvučnog prikaza različitih dijelova slike.',
	findLabel: 'Pronađi',
	toNextMatch: 'Dalje',
	closeDialog: 'Zatvori',
	findDialogShown: 'Dijalog „Pronađi” prikazan',
	findDialogHidden: 'Dijalog „Pronađi” skriven',
	focusedFoundText: (matchIdx, totalMatches) => `Prikaz podudaranja ${matchIdx} od ${totalMatches}`,
	anyDevicePanning: 'Pomicanje s bilo kojim uređajem',
	copied: (count) => `Kopirane stavke: ${count}`,
	pasted: (count) => `Umetnute stavke: ${count}`,
	toolEnabledAnnouncement: (toolName) => `Alat „${toolName}” uključen`,
	toolDisabledAnnouncement: (toolName) => `Alat „${toolName}” isključen`,
	updatedViewport: 'Transformirano vidno područje',
	transformedElements: (elemCount, action) =>
		`Transformiran ${elemCount} element${elemCount === 1 ? '' : 'a'} (${action})`,
	resizeOutputCommand: (newSize) => `Promijenjena veličina slike na ${newSize.w} × ${newSize.h}`,
	enabledAutoresizeOutputCommand: 'Automatska promjena veličine rezultata uključena',
	disabledAutoresizeOutputCommand: 'Automatska promjena veličine rezultata isključena',
	addComponentAction: (componentDescription) => `${componentDescription} dodan`,
	eraseAction: (componentDescription, numElems) =>
		`Broj izbrisanih ${componentDescription}: ${numElems}`,
	duplicateAction: (componentDescription, numElems) =>
		`Broj duplicirani ${componentDescription}: ${numElems}`,
	unionOf: (actionDescription, actionCount) => `Unija: ${actionCount} ${actionDescription}`,
	inverseOf: (actionDescription) => `Suprotno od ${actionDescription}`,
	elements: 'Elementi',
	erasedNoElements: 'Ništa nije izbrisano',
	duplicatedNoElements: 'Ništa nije duplicirano',
	rotatedBy: (degrees) =>
		`Okrenuto ${Math.abs(degrees)} stupnjeva ${degrees < 0 ? 'clockwise' : 'counter-clockwise'}`,
	movedLeft: 'Pomaknuto ulijevo',
	movedUp: 'Pomaknuto prema gore',
	movedDown: 'Pomaknuto prema dolje',
	movedRight: 'Pomaknuto udesno',
	zoomedOut: 'Umanjeno',
	zoomedIn: 'Uvečano',
	andNMoreCommands: (count) => `I još ${count} naredbi.`,
	selectedElements: (count) => `Odabrano ${count} element${count === 1 ? '' : 'a'}`,
	unlabeledImageNode: 'Neoznačena slika',
	stroke: 'Potez',
	svgObject: 'SVG objekt',
	emptyBackground: 'Prazna pozadina',
	gridBackground: 'Mrežasta pozadina',
	filledBackgroundWithColor: (color) => `Ispunjena pozadina (${color})`,
	text: (text) => `Tekstualni objekt: ${text}`,
	imageNode: (label) => `Slika: ${label}`,
	restyledElement: (elementDescription) => `Promijenjen stil za ${elementDescription}`,
	pathNodeCount: (count) => `Broj vidljivih objekta staze: ${count}.`,
	textNodeCount: (count) => `Broj vidljivih tekstualnih čvorova: ${count}.`,
	imageNodeCount: (count) => `Broj vidljivih slikovnih čvorova: ${count}.`,
	textNode: (content) => `Tekst: ${content}`,
	rerenderAsText: 'Ponovo iscrtaj kao tekst',
	accessibilityInputInstructions:
		'Pritisni „t” za čitanje sadržaja vidnog područja kao teksta. Koristi strelice za pomicanje prikaza, klikni i povuci za crtanje poteza. Pritisni „w” za uvećani prikaz, a „s” za umanjeni prikaz.',
	loading: (percentage) => `Učitavanje ${percentage} % …`,
	imageEditor: 'Uređivač slika',
	doneLoading: 'Učitavanje gotovo',
	undoAnnouncement: (commandDescription) => `Poništeno: ${commandDescription}`,
	redoAnnouncement: (commandDescription) => `Ponovljeno: ${commandDescription}`,
	softwareLibraries: 'Biblioteke',
	developerInformation: 'Informacije za programere',
};

export default localization;
