import { defaultEditorLocalization, EditorLocalization } from '../localization';

// Slovak localization
const localization: EditorLocalization = {
	...defaultEditorLocalization,
	help: 'Pomoc',
	helpHidden: 'Skrytá pomoc',
	next: 'Ďalšie',
	previous: 'Prechádzajúce',
	close: 'Zavrieť',
	helpScreenNavigationHelp: 'Kliknutím na ovládací prvok získate viac informácií.',
	helpControlsAccessibilityLabel: 'Ovládacie prvky: Aktivujte ovládací prvok, ktorý zobrazí pomoc.',
	pen: 'Pero',
	eraser: 'Guma',
	select: 'Vybrať',
	handTool: 'Posun',
	zoom: 'Priblížiť',
	image: 'Obrázok',
	reformatSelection: 'Výber formátu',
	inputAltText: 'Alternatívny text',
	decreaseImageSize: 'Zmenšiť veľkosť',
	resetImage: 'Obnoviť',
	chooseFile: 'Vybrať súbor',
	dragAndDropHereOrBrowse: 'Presuňte sem alebo {{prehľadávať}}',
	submit: 'Odoslať',
	addAll: 'Pridať všetko',
	cancel: 'Zrušiť',
	resetView: 'Obnoviť zobrazenie',
	thicknessLabel: 'Hrúbka',
	colorLabel: 'Farba',
	fontLabel: 'Písmo',
	textSize: 'Veľkosť',
	resizeImageToSelection: 'Zmena veľkosti obrázka podľa výberu',
	deleteSelection: 'Vymazať výber',
	exit: 'Ukončiť',
	save: 'Uložiť',
	undo: 'Späť',
	redo: 'Opakovať',
	fullStrokeEraser: 'Guma s plným ťahom',
	selectPenType: 'Typ pera',
	selectShape: 'Tvar',
	pickColorFromScreen: 'Vybrať farbu z obrazovky',
	clickToPickColorAnnouncement: 'Kliknutím na obrazovku vyberte farbu',
	colorSelectionCanceledAnnouncement: 'Výber farby zrušený',
	documentProperties: 'Strana',
	backgroundColor: 'Farba pozadia',
	imageWidthOption: 'Šírka',
	imageHeightOption: 'Výška',
	useGridOption: 'Mriežka',
	enableAutoresizeOption: 'Automatická zmena veľkosti',
	toggleOverflow: 'Viac',
	about: 'O aplikácii',
	inputStabilization: 'Stabilizácia',
	strokeAutocorrect: 'Automatická oprava',
	pressureSensitivity: 'Tlak',
	touchPanning: 'Posúvanie dotykom',
	roundedTipPen: 'Okrúhle',
	roundedTipPen2: 'Viacčiarové',
	flatTipPen: 'Ploché',
	arrowPen: 'Šípka',
	linePen: 'Čiara',
	outlinedRectanglePen: 'Obrys obdĺžnika',
	filledRectanglePen: 'Plný obdĺžnik',
	outlinedCirclePen: 'Kružnica',
	paste: 'Vložiť',
	fileInput__loading: 'Načítavanie...',
	handDropdown__zoomInHelpText: 'Priblížiť.',
	handDropdown__zoomOutHelpText: 'Oddialiť.',
	selectionTool: 'Výber',
	eraserTool: 'Guma',
	twoFingerPanZoomTool: 'Posun a priblíženie',
	undoRedoTool: 'Späť/Opakovať',
	selectionMenu__delete: 'Vymazať',
	selectionMenu__paste: 'Vložiť',
	copyPasteError__heading: 'Kopírovať/vložiť',
	closeDialog: 'Zavrieť',
};

export default localization;
