// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('node:fs');

// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('node:path');

console.log('Copying licenses...');
const rootDir = path.dirname(__dirname);
const distDir = path.join(rootDir, 'dist');
fs.copyFileSync(path.join(rootDir, 'dependency-licenses.txt'), path.join(distDir, 'licenses.txt'));

console.log('Writing version...');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const version = require('../package.json').version;
fs.writeFileSync(
	path.join(rootDir, 'src', 'constants.autogenerated.ts'),
	`
export default {
	version: ${JSON.stringify(version)},
};
`,
);
